apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  POSTGRES_HOST: {{ .Values.secrets.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.secrets.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDatabase | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  BOOTSTRAP_DB: {{ .Values.secrets.bootstrapDb | quote }}
  BOOTSTRAP_POSTGRES_HOST: {{ .Values.secrets.bootstrapPostgresHost | quote }}
  BOOTSTRAP_POSTGRES_PORT: {{ .Values.secrets.bootstrapPostgresPort | quote }}
  BOOTSTRAP_POSTGRES_ADMIN_DB: {{ .Values.secrets.bootstrapPostgresAdminDb | quote }}
  BOOTSTRAP_POSTGRES_ADMIN_USER: {{ .Values.secrets.bootstrapPostgresAdminUser | quote }}
  BOOTSTRAP_POSTGRES_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapPostgresAdminPassword | quote }}
  RESET_PASSWORD_BASE_URL: {{ .Values.secrets.resetPasswordBaseUrl | quote }}
